name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Debug Files
        run: |
          echo "Listing directory contents..."
          ls -la
          echo "Content of config.js.example:"
          cat config.js.example

      - name: Create config.js from example
        run: |
          echo "Creating config.js from example..."
          cp config.js.example config.js
          echo "Replacing API key placeholder..."
          # Print the sed command being used (with key redacted)
          echo "sed command: s/YOUR_NEW_API_KEY_HERE/<API_KEY>/g"
          sed -i "s/YOUR_NEW_API_KEY_HERE/${{ secrets.GOOGLE_MAPS_API_KEY }}/g" config.js || {
            echo "Error: sed command failed"
            exit 1
          }
          echo "Content of generated config.js (with key redacted):"
          cat config.js | sed 's/AIza[0-9A-Za-z-_]*/<API_KEY_REDACTED>/g'

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4